/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 03 18:13:51 GMT 2018
 */

package ch.ge.ve.commons.crypto.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ch.ge.ve.commons.crypto.exceptions.PrivateKeyPasswordMismatchException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PrivateKeyPasswordMismatchException_ESTest extends PrivateKeyPasswordMismatchException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PrivateKeyPasswordMismatchException privateKeyPasswordMismatchException0 = new PrivateKeyPasswordMismatchException("");
      PrivateKeyPasswordMismatchException privateKeyPasswordMismatchException1 = new PrivateKeyPasswordMismatchException((String) null, privateKeyPasswordMismatchException0, true, true);
      assertFalse(privateKeyPasswordMismatchException1.equals((Object)privateKeyPasswordMismatchException0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PrivateKeyPasswordMismatchException privateKeyPasswordMismatchException0 = new PrivateKeyPasswordMismatchException("");
      PrivateKeyPasswordMismatchException privateKeyPasswordMismatchException1 = new PrivateKeyPasswordMismatchException(privateKeyPasswordMismatchException0);
      assertFalse(privateKeyPasswordMismatchException1.equals((Object)privateKeyPasswordMismatchException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PrivateKeyPasswordMismatchException privateKeyPasswordMismatchException0 = new PrivateKeyPasswordMismatchException("");
      PrivateKeyPasswordMismatchException privateKeyPasswordMismatchException1 = new PrivateKeyPasswordMismatchException("iBzf$C", privateKeyPasswordMismatchException0);
      assertFalse(privateKeyPasswordMismatchException1.equals((Object)privateKeyPasswordMismatchException0));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PrivateKeyPasswordMismatchException privateKeyPasswordMismatchException0 = new PrivateKeyPasswordMismatchException("");
      PrivateKeyPasswordMismatchException privateKeyPasswordMismatchException1 = null;
      try {
        privateKeyPasswordMismatchException1 = new PrivateKeyPasswordMismatchException("", privateKeyPasswordMismatchException0, false, false);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.evosuite.runtime.mock.java.lang.MockException", e);
      }
  }
}
